### ISSUE TITLE
found a typo in Loader.php

### ISSUE THREAD

**Issue by hubylizer** [eloquent/schemer#21]
Hi I am not shure but I guess that in 
src/Eloquent/Schemer/Loader/Loader.php on line 74
there should be a $this instead of $thia

**Comment by ezzatron** [comment]
For what it's worth, the main branch of this project is pretty old by now. I was working on a [rewrite](https://github.com/eloquent/schemer/tree/feature/rewrite) at some point, but it's not high on my priority list. There is a more well-maintained project over at [justinrainbow/json-schema](https://github.com/justinrainbow/json-schema) that may be a better choice.

In any case, I appreciate the message. Thanks!
